# Generated by Django 5.0 on 2024-07-19 23:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profesor_facultades_alter_facultad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
    ]
